export const roleEndpoints = {
  roles: '/api/system/roles',
  rolesBatch: '/api/system/roles/batch',
  exportRoles: '/api/system/roles/export',
  options: '/api/system/roles/options',
  role: (id: string) => `/api/system/roles/${id}`,
  status: (id: string) => `/api/system/roles/${id}/status`,
  dataScope: (id: string) => `/api/system/roles/${id}/data-scope`,
  users: (id: string) => `/api/system/roles/${id}/users`,
  usersBatch: (id: string) => `/api/system/roles/${id}/users/batch`,
  roleUser: (id: string, userId: string) => `/api/system/roles/${id}/users/${userId}`,
  roleMenus: (id: string) => `/api/system/roles/${id}/menus`,
  roleDepts: (id: string) => `/api/system/roles/${id}/depts`,
  roleMenuTreeSelect: (id: string) => `/api/system/menus/role-tree-select/${id}`,
  roleDeptTreeSelect: (id: string) => `/api/system/roles/${id}/dept-tree-select`,
} as const;
