services:
  taco:
    build: .
    command: ['--config', '/app/config/config.yaml']
    ports:
      - '127.0.0.1:3000:3000'
    restart: unless-stopped
    volumes:
      - /etc/taco/config.yaml:/app/config/config.yaml:ro
      - taco-data:/app/local-data
    healthcheck:
      test: ['CMD', 'curl', '--fail', '--silent', '--show-error', 'http://127.0.0.1:3000/health']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  taco-data:
