export const systemEndpoints = {
  depts: '/api/system/depts',
  deptTreeSelect: '/api/system/depts/tree-select',
  deptExclude: (id: string) => `/api/system/depts/exclude/${id}`,
  dept: (id: string) => `/api/system/depts/${id}`,
  deptSort: (id: string) => `/api/system/depts/${id}/sort`,
  deptSortBatch: '/api/system/depts/sort',
  posts: '/api/system/posts',
  postsBatch: '/api/system/posts/batch',
  roleDeptTreeSelect: (id: string) => `/api/system/roles/${id}/dept-tree-select`,
  postOptions: '/api/system/posts/options',
  post: (id: string) => `/api/system/posts/${id}`,
  dictTypes: '/api/system/dict-types',
  dictTypesBatch: '/api/system/dict-types/batch',
  dictTypeOptions: '/api/system/dict-types/options',
  dictTypeCache: '/api/system/dict-types/cache',
  dictType: (id: string) => `/api/system/dict-types/${id}`,
  dictData: '/api/system/dict-data',
  dictDataBatch: '/api/system/dict-data/batch',
  dictDataByType: (dictType: string) => `/api/system/dict-data/type/${dictType}`,
  dictDatum: (id: string) => `/api/system/dict-data/${id}`,
  configs: '/api/system/configs',
  configsBatch: '/api/system/configs/batch',
  configCache: '/api/system/configs/cache',
  configByKey: (key: string) => `/api/system/configs/key/${key}`,
  config: (id: string) => `/api/system/configs/${id}`,
} as const;
