CREATE FUNCTION system_log_search_ngrams(value TEXT)
RETURNS TEXT[]
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
RETURN ARRAY(
    WITH normalized AS (
        SELECT lower(value) AS content
    ),
    tokens AS (
        SELECT SUBSTRING(content FROM position FOR 1) AS token
        FROM normalized, generate_series(1, char_length(content)) AS position
        UNION
        SELECT SUBSTRING(content FROM position FOR 2) AS token
        FROM normalized, generate_series(1, GREATEST(char_length(content) - 1, 0)) AS position
    )
    SELECT DISTINCT token
    FROM tokens
    ORDER BY token
);

ALTER TABLE sys_system_log
    ADD COLUMN ingested_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN search_ngrams TEXT[] GENERATED ALWAYS AS (system_log_search_ngrams(message || ' ' || fields::text)) STORED;

CREATE INDEX idx_sys_system_log_ingested_seq
    ON sys_system_log (ingested_seq DESC);

CREATE INDEX idx_sys_system_log_search_ngrams
    ON sys_system_log USING GIN (search_ngrams);

DROP INDEX idx_sys_system_log_target_cursor;

CREATE INDEX idx_sys_system_log_target_cursor
    ON sys_system_log (target text_pattern_ops, occurred_at DESC, id DESC);
